# Generated by Django 5.1.5 on 2025-01-29 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBIN', models.CharField(max_length=16, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('catagory', models.CharField(choices=[('PHYSICS', 'Physics'), ('CHEMISTRY', 'Chemistry'), ('MATHS', 'Maths'), ('BIOLOGY', 'Biology')], default='PHYSIC', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_number', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('Books', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.books')),
            ],
        ),
    ]
