# Generated by Django 5.1.5 on 2025-01-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='ISBIN',
            field=models.IntegerField(unique=True),
        ),
    ]
