# Generated by Django 5.1.5 on 2025-01-29 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_books_isbin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
