# Generated by Django 5.1.5 on 2025-01-29 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_rename_books_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Books',
            new_name='book',
        ),
    ]
