# Generated by Django 5.1.5 on 2025-01-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_rename_books_student_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='catagory',
            field=models.CharField(choices=[('PHYSICS', 'Physics'), ('CHEMISTRY', 'Chemistry'), ('MATHS', 'Maths'), ('BIOLOGY', 'Biology'), ('ZOOLOGY', 'Zoology')], default='PHYSIC', max_length=20),
        ),
    ]
