# Generated by Django 5.1.5 on 2025-01-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_alter_student_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ISBIN',
            new_name='ISBN',
        ),
    ]
