# Generated by Django 5.1.5 on 2025-01-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_alter_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discription',
            field=models.TextField(max_length=100),
        ),
    ]
